import {test,expect} from '@playwright/test';
for(const width of [390,1440]) test(`attention sources stay distinct from workstream counters ${width}`,async({page})=>{
 await page.setViewportSize({width,height:1000});
 await page.goto('/#/organizations/knowledge?persona=leo');
 const summary=page.getByLabel('Attention counter sources');
 await expect(summary).toContainText('0 local session signals');
 const work=page.getByRole('region',{name:'Organization workstreams'});
 const before=await work.locator('.coordination-counts').allTextContents();
 await expect(page.getByLabel('Workstream counter source')).toContainText('do not follow local contribution receipts');
 await page.goto('/#/organizations/knowledge/contributions/K-01-H?persona=leo');
 await page.getByLabel('Contribution text').fill('Guide text.');
 await page.getByLabel('Delivery note',{exact:true}).fill('Scope note.');
 await page.getByRole('checkbox').check();
 await page.getByRole('button',{name:'Review delivery'}).click();
 await page.getByRole('button',{name:'Record local delivery'}).click();
 await page.getByRole('button',{name:'View Organization',exact:true}).click();
 await expect(summary).toContainText('1 local session signals');
 const needs=page.getByRole('region',{name:'Concrete coordination needs'});
 await expect(needs.getByText('Local session observation · resets on reload')).toBeVisible();
 await expect(needs.getByText('Authored scenario · fixed context').first()).toBeVisible();
 expect(await work.locator('.coordination-counts').allTextContents()).toEqual(before);
 await page.getByRole('button',{name:'View all organization attention'}).click();
 await expect(page.getByText('Local session observation · resets on reload')).toBeVisible();
 await page.getByRole('button',{name:'Open next step · Maya · sample receiver'}).click();
 await page.getByRole('button',{name:'Record sample receipt · draft-01'}).click();
 await page.getByRole('button',{name:'Back to Organization',exact:true}).click();
 await expect(summary).toContainText('0 local session signals');
 expect(await work.locator('.coordination-counts').allTextContents()).toEqual(before);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
